### ISSUE TITLE
Improve handling of retired parlamentarian

### ISSUE THREAD

**Issue by scito** [labsletemps/parliament-extension#11]
Retired parliamentarian are not shown in a good way.

Proposition: “XY ist seit ???? nicht mehr Mitglied der eidgenössischen Räte.” 

Example with retired parlamentarian: https://www.beobachter.ch/politik/bundesrat-lukrative-jobli-fur-ex-parlamentarier

**Comment by palrogg** [comment]
Yes, it's in progress! I'm sorry, I couldn't follow the pace lately.

My plan is actually to write (in fr / de):

*Former* <State/National Councillor>
Date_from Date_to

In German: "Ehemalig" / "Ehemalige", right?

What do you think of it?

Best
P.

**Comment by scito** [comment]
Ehemaliger Parlamentarier
Ehemalige Parlamentarierin

**Comment by palrogg** [comment]
Actually: no historic data ([example](https://lobbywatch.ch/fr/daten/parlamentarier/Parliamentarian-237/Werner%20Luginb%C3%BChl)) so no need for this. Former councillors removed
