### ISSUE TITLE
When malformed JSON is returned by API, it creates a JS error and breaks the website.

### ISSUE THREAD

**Issue by yvmarques** [labsletemps/parliament-extension#12]
Looks like the API can return a malformed JSON and jQuery is not able to parse it, which creates an error on the website and breaks the JavaScript (see screenshot).
<img width="862" alt="Capture d’écran 2020-04-07 à 12 52 35" src="https://user-images.githubusercontent.com/176204/78661894-cd879680-78cf-11ea-8bbd-f9a72339503d.png">

**Comment by palrogg** [comment]
Good point, I'll catch JSON handling errors

**Comment by palrogg** [comment]
Done in e8a976c89d10a6f0a5c4457ae68b3108f1c21f48
