### ISSUE TITLE
Too big on mobile devices

### ISSUE THREAD

**Issue by scito** [labsletemps/parliament-extension#4]
I'm using a Samsung Galaxy S6 device with Firefox.

The parliament extension window is too big for this device. The extension grows the right size of the page. After closing the extension window, the page shrinks again to normal size.

![Screenshot_20191012-080253](https://user-images.githubusercontent.com/876593/66695930-68a80680-ecc7-11e9-8e6c-ed3cc395a6b4.png)

https://www.beobachter.ch/politik/lobbyisten-eigeninteressen-waren-starker

I suggest using a responsive design for the extension.

**Comment by palrogg** [comment]
Done for next update
(Screen width < 500px: max tooltip width = 98%)

![Capture d’écran 2019-12-23 à 11 23 55](https://user-images.githubusercontent.com/12730304/71352503-c33aca00-2576-11ea-9b70-9a0391f83bde.png)
